### ISSUE TITLE
Listing 4.015.sql - No Rows

### ISSUE THREAD

**Issue by richardbroersma** [TexanInParis/Effective-SQL#13]
Neither query supplies produces any rows in the result set.

**Comment by TexanInParis** [comment]
That is the correct result because it turns out that all customers who ordered a skateboard did also order all the corrective gear - perhaps in other orders.  If I had modified it to require all to be in the same order, we would have had some results.  Neither 4.15 nor 4.16 (the versions that use LIKE) will return any rows.
